apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ignacio6779/custom-openresty:latest
        command: ["/usr/local/openresty/bin/openresty", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/roles.lua
            subPath: roles.lua
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/upstreams.conf
            subPath: upstreams.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/chat.conf
            subPath: chat.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/faq.conf
            subPath: faq.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/login.conf
            subPath: login.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/map.conf
            subPath: map.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/test.conf
            subPath: test.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/user.conf
            subPath: user.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/conf.d/locations/schedule.conf
            subPath: schedule.conf
            name: nginx-config-volume
          - mountPath: /usr/local/openresty/lualib/resty/validate_jwt.lua
            subPath: validate_jwt.lua
            name: nginx-config-volume
          - mountPath: /var/run/openresty
            name: run-openresty-dir
          - name: keycloak-public-key
            mountPath: /etc/secrets
            readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: run-openresty-dir
          emptyDir: {}
        - name: keycloak-public-key
          secret:
            secretName: keycloak-public-key
